#!/usr/bin/env bash
#
# Generates Word reference PDFs for the fixtures that do not have one yet.
#
# These references are the ground truth for the Tier 3 comparison: they are the only thing that
# can tell us we agree with Word rather than merely agreeing with our own last run. Committed to
# the repo, so this normally needs running only when a fixture is added or changed.
#
# Requires Microsoft Word, and macOS. Word is driven through AppleScript.
#
#   tools/make-reference-pdfs.sh            generate only what is missing
#   tools/make-reference-pdfs.sh --force    regenerate everything
#   tools/make-reference-pdfs.sh --list     show what is missing and exit
#
# First run: macOS will ask permission for your terminal to control Word, and Word itself may ask
# for access to the fixtures folder. Both prompts need a click; the script waits for them.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FIXTURES="$REPO_ROOT/tests/n8PDF.Tests/Fixtures/Minimal"
REFERENCES="$REPO_ROOT/tests/n8PDF.Tests/Fixtures/Reference"

FORCE=0
LIST_ONLY=0
for arg in "$@"; do
    case "$arg" in
        --force) FORCE=1 ;;
        --list)  LIST_ONLY=1 ;;
        -h|--help) sed -n '2,20p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) echo "unknown option: $arg" >&2; exit 2 ;;
    esac
done

if [[ "$(uname)" != "Darwin" ]]; then
    echo "This script drives Microsoft Word through AppleScript and only runs on macOS." >&2
    echo "On another platform, export the fixtures to PDF by hand into:" >&2
    echo "  $REFERENCES" >&2
    exit 1
fi

if [[ ! -d "/Applications/Microsoft Word.app" ]]; then
    echo "Microsoft Word is not installed at /Applications/Microsoft Word.app." >&2
    exit 1
fi

mkdir -p "$REFERENCES"

# The fixtures are generated by the test suite rather than committed as source, so make sure they
# are on disk and current before exporting anything from them.
if [[ ! -d "$FIXTURES" ]] || [[ -z "$(ls -A "$FIXTURES" 2>/dev/null)" ]]; then
    echo "Materialising fixtures..."
    dotnet test "$REPO_ROOT/n8PDF.sln" \
        --filter "FullyQualifiedName~Fixtures_are_written_to_disk" >/dev/null 2>&1 || true
fi

shopt -s nullglob
fixtures=()
for candidate in "$FIXTURES"/*.docx; do
    # Word drops an owner-lock file named "~$<document>.docx" beside any document it has open.
    # They are not fixtures, and exporting one would fail or produce garbage.
    [[ "$(basename "$candidate")" == '~$'* ]] && continue
    fixtures+=("$candidate")
done
shopt -u nullglob

if [[ ${#fixtures[@]} -eq 0 ]]; then
    echo "No fixtures found in $FIXTURES." >&2
    echo "Run 'dotnet test' once to generate them." >&2
    exit 1
fi

# Work out what actually needs doing before launching Word.
missing=()
for docx in "${fixtures[@]}"; do
    name="$(basename "$docx" .docx)"
    if [[ $FORCE -eq 1 || ! -f "$REFERENCES/$name.pdf" ]]; then
        missing+=("$name")
    fi
done

if [[ ${#missing[@]} -eq 0 ]]; then
    echo "All ${#fixtures[@]} fixture(s) already have a reference PDF."
    exit 0
fi

if [[ $LIST_ONLY -eq 1 ]]; then
    echo "Missing reference PDFs (${#missing[@]}):"
    printf '  %s\n' "${missing[@]}"
    exit 0
fi

echo "Generating ${#missing[@]} reference PDF(s) with Microsoft Word..."
echo

# Word is driven against copies in a temp directory rather than against the repo. It drops an
# owner-lock file beside every open document and only removes it on close, so a run that dies
# midway would otherwise leave lock files in the fixtures folder and make the next run fail with
# "file in use".
# Word recalculates only the page-dependent fields when it exports — PAGE, SECTION, SEQ and the
# like — and leaves every other field showing whatever it last computed. A fixture written by hand
# has no last computed value, so those fields would export blank. For the fixtures named here the
# fields are updated first, which is the only way to get Word's own answer for them.
UPDATES_FIELDS=("fields" "styleref" "toc" "index" "formulas" "merge")

updates_fields() {
    local name="$1"
    for candidate in "${UPDATES_FIELDS[@]}"; do
        [[ "$candidate" == "$name" ]] && return 0
    done
    return 1
}

WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

failed=()
for name in "${missing[@]}"; do
    pdf="$REFERENCES/$name.pdf"

    printf '  %-24s ' "$name"
    rm -f "$pdf"

    cp "$FIXTURES/$name.docx" "$WORKDIR/$name.docx"
    work_pdf="$WORKDIR/$name.pdf"

    # Several things here are non-obvious and were each found the hard way:
    #   - "open" does not return a document reference in Word for Mac, so the document has to be
    #     located afterwards.
    #   - It must be located *by name*, not through "active document". If a previous export left
    #     a document open, the active one is the wrong document and Word will cheerfully export
    #     it under this fixture's name — producing a reference PDF whose contents belong to a
    #     different fixture, which is far worse than a failure because it looks like a result.
    #   - "active document" does not understand "close", but an indexed "document N" reference
    #     does.
    #   - stderr is captured rather than discarded; without the AppleScript error text a failure
    #     here is completely opaque.
    # The default AppleEvent timeout is two minutes, and Word exceeds it on a cold start; the
    # explicit timeout covers that. Opening is also not synchronous — Word returns before the
    # document is in its collection — so the document is polled for rather than assumed present,
    # which is what caused a cascade of "did not open" failures once the first export was slow.
    update_fields=0
    updates_fields "$name" && update_fields=1

    error=$(osascript \
        -e 'on run argv' \
        -e '  set inFile to POSIX file (item 1 of argv)' \
        -e '  set outPath to (item 2 of argv)' \
        -e '  set wanted to (item 3 of argv)' \
        -e '  set updateFields to (item 4 of argv) is "1"' \
        -e '  with timeout of 300 seconds' \
        -e '    tell application "Microsoft Word"' \
        -e '      open inFile' \
        -e '      set theDoc to missing value' \
        -e '      repeat 60 times' \
        -e '        repeat with i from 1 to (count of documents)' \
        -e '          if name of document i is wanted then set theDoc to document i' \
        -e '        end repeat' \
        -e '        if theDoc is not missing value then exit repeat' \
        -e '        delay 0.5' \
        -e '      end repeat' \
        -e '      if theDoc is missing value then error "Word did not open a document named " & wanted' \
        -e '      if updateFields then' \
        -e '        repeat with i from 1 to (count of fields of theDoc)' \
        -e '          update field (field i of theDoc)' \
        -e '        end repeat' \
        -e '      end if' \
        -e '      save as theDoc file name outPath file format format PDF' \
        -e '      repeat with i from (count of documents) to 1 by -1' \
        -e '        if name of document i is wanted then close document i saving no' \
        -e '      end repeat' \
        -e '    end tell' \
        -e '  end timeout' \
        -e 'end run' \
        "$WORKDIR/$name.docx" "$work_pdf" "$name.docx" "$update_fields" 2>&1) && [[ -s "$work_pdf" ]]

    if [[ -s "$work_pdf" ]]; then
        mv "$work_pdf" "$pdf"
        printf 'ok  (%s)\n' "$(du -h "$pdf" | cut -f1 | tr -d ' ')"
    else
        printf 'FAILED\n'
        [[ -n "$error" ]] && printf '      %s\n' "$error"
        failed+=("$name")
    fi
done

echo
if [[ ${#failed[@]} -gt 0 ]]; then
    echo "Failed to export ${#failed[@]} fixture(s):" >&2
    printf '  %s\n' "${failed[@]}" >&2
    echo >&2
    echo "If Word showed a dialog, answer it and re-run. Word is sandboxed, so the first export" >&2
    echo "from a new folder usually needs a one-time 'Grant Access' click." >&2
    echo >&2
    echo "If every fixture failed with 'Word did not open a document named ...', Word is wedged:" >&2
    echo "it accepts the open command and silently does nothing. Quit Word and re-run. Dismiss" >&2
    echo "any dialog it shows on the way out." >&2
    echo "You can also export by hand: open the .docx in Word and save as PDF into" >&2
    echo "  $REFERENCES" >&2
    exit 1
fi

echo "Done. ${#missing[@]} reference PDF(s) written to:"
echo "  $REFERENCES"
echo
echo "Commit them, then run: dotnet test"
