#!/usr/bin/env python3
"""Writes the Unicode tables the bidirectional algorithm reads.

The classes come from Python's own copy of the Unicode character database, so what lands in the
library is the standard's answer rather than a guess at it. Run it when a newer Unicode is worth
having; the output is committed, since the library carries no dependencies of its own.

    tools/make-bidi-tables.py > src/n8PDF/Text/BidiTables.cs
"""

import sys
import unicodedata

MAX = 0x110000

# The default class of an unassigned character depends on where it lies: the standard sets aside
# whole blocks for scripts that are written right to left, so a character not yet assigned in one
# of them is right-to-left rather than left-to-right.
DEFAULTS = [
    (0x0600, 0x07BF, "AL"), (0x0860, 0x08FF, "AL"), (0xFB50, 0xFDCF, "AL"),
    (0xFDF0, 0xFDFF, "AL"), (0xFE70, 0xFEFF, "AL"),
    (0x00010D00, 0x00010D3F, "AL"), (0x00010EC0, 0x00010EFF, "AL"),
    (0x00010F30, 0x00010F6F, "AL"), (0x0001EC70, 0x0001ECBF, "AL"),
    (0x0001ED00, 0x0001ED4F, "AL"), (0x0001EE00, 0x0001EEFF, "AL"),
    (0x0590, 0x05FF, "R"), (0x07C0, 0x085F, "R"), (0xFB1D, 0xFB4F, "R"),
    (0x00010800, 0x00010CFF, "R"), (0x00010D40, 0x00010EBF, "R"),
    (0x00010F00, 0x00010F2F, "R"), (0x00010F70, 0x00010FFF, "R"),
    (0x0001E800, 0x0001EC6F, "R"), (0x0001ECC0, 0x0001ECFF, "R"),
    (0x0001ED50, 0x0001EDFF, "R"), (0x0001EF00, 0x0001EFFF, "R"),
    (0x20A0, 0x20CF, "ET"),
]

def default_of(code):
    for start, end, cls in DEFAULTS:
        if start <= code <= end:
            return cls
    return "L"

def classes():
    for code in range(MAX):
        name = unicodedata.bidirectional(chr(code))
        yield code, name if name else default_of(code)

def ranges():
    out = []
    start = 0
    current = None
    for code, cls in classes():
        if cls != current:
            if current is not None:
                out.append((start, code - 1, current))
            start, current = code, cls
    out.append((start, MAX - 1, current))
    return out

def brackets():
    """The paired brackets, which the algorithm matches up so that (א) reads as it should."""
    pairs = []
    for code in range(MAX):
        ch = chr(code)
        if unicodedata.category(ch) != "Ps" or not unicodedata.mirrored(ch):
            continue
        try:
            name = unicodedata.name(ch)
        except ValueError:
            continue
        other = name.replace("LEFT", "\x00").replace("RIGHT", "LEFT").replace("\x00", "RIGHT")
        try:
            close = unicodedata.lookup(other)
        except KeyError:
            continue
        if unicodedata.category(close) == "Pe":
            pairs.append((code, ord(close)))
    return pairs

def mirrors():
    """What a character is drawn as when the line around it runs the other way."""
    out = []
    for code in range(MAX):
        ch = chr(code)
        if not unicodedata.mirrored(ch):
            continue
        try:
            name = unicodedata.name(ch)
        except ValueError:
            continue
        other = name.replace("LEFT", "\x00").replace("RIGHT", "LEFT").replace("\x00", "RIGHT")
        if other == name:
            other = name.replace("LESS-THAN", "\x00").replace("GREATER-THAN", "LESS-THAN").replace("\x00", "GREATER-THAN")
        if other == name:
            continue
        try:
            out.append((code, ord(unicodedata.lookup(other))))
        except KeyError:
            continue
    return out

def emit(rows, per_line, width):
    for i in range(0, len(rows), per_line):
        print("        " + " ".join(rows[i:i + per_line]).rstrip())

print(f"""// Generated by tools/make-bidi-tables.py from Unicode {unicodedata.unidata_version}. Do not edit.

namespace n8PDF.Text;

/// <summary>
/// What the Unicode character database says about which way each character runs.
/// </summary>
/// <remarks>
/// Generated rather than written, from the database itself, because it is a hundred thousand
/// answers and any of them typed by hand would be a hundred thousand chances to be wrong. The
/// library carries no dependencies, so the table is committed as source; the script that makes it
/// again is in <c>tools</c>.
/// </remarks>
internal static class BidiTables
{{
    /// <summary>Where each run of characters of one class begins, and the class it is.</summary>
    internal static readonly int[] RangeStarts =
    [""")

rows = ranges()
emit([f"0x{start:X}," for start, _, _ in rows], 12, 0)
print("    ];\n")
print("    internal static readonly BidiClass[] RangeClasses =\n    [")
emit([f"BidiClass.{cls}," for _, _, cls in rows], 8, 0)
print("    ];\n")

print("    /// <summary>The brackets the algorithm pairs up, opening then closing.</summary>")
print("    internal static readonly int[] BracketPairs =\n    [")
emit([f"0x{a:X}, 0x{b:X}," for a, b in brackets()], 6, 0)
print("    ];\n")

print("    /// <summary>What each character is drawn as where the line runs the other way.</summary>")
print("    internal static readonly int[] Mirrored =\n    [")
emit([f"0x{a:X}, 0x{b:X}," for a, b in mirrors()], 6, 0)
print("    ];")
print("}")
