#!/usr/bin/env python3
"""Writes the table of American English hyphenation patterns.

Where a word may be broken is not something that can be worked out from its letters: it is a
matter of a language's own habits, and every typesetting program that does it carries a table.
Word carries one; this turns the public one into source, since the library has no dependencies and
the answer must not depend on a file being present at run time.

The patterns are Liang's, in the form TeX has distributed them in since 1990, and the algorithm
they are read by is his: every substring of a word matched against the table, the largest number
each position is given by any of them kept, and an odd number meaning a break is allowed there.

    curl -O https://raw.githubusercontent.com/hyphenation/tex-hyphen/master/hyph-utf8/tex/generic/hyph-utf8/patterns/tex/hyph-en-us.tex
    tools/make-hyphenation-tables.py hyph-en-us.tex > src/n8PDF/Text/HyphenationTables.cs

The file's own licence asks that its copyright notice be preserved, and the generated source
carries it.
"""

import re
import sys

NOTICE = """// Hyphenation patterns for American English.
// Copyright (C) 1990, 2004, 2005 Gerard D.C. Kuiken.
//
// Copying and distribution of this file, with or without modification, are permitted in any
// medium without royalty provided the copyright notice and this notice are preserved."""


def wrap(items, width=100, indent="        "):
    """Fills lines to a width, so that the generated source can be read."""
    lines = []
    line = indent

    for item in items:
        if len(line) + len(item) + 1 > width and line != indent:
            lines.append(line)
            line = indent
        line += item + " "

    if line.strip():
        lines.append(line.rstrip())

    return "\n".join(line.rstrip() for line in lines)


def main(path):
    text = open(path, encoding="utf-8").read()

    # TeX comments run from a per cent sign to the end of the line, and the file opens its list of
    # patterns with one.
    text = re.sub(r"(?<!\\)%.*", "", text)

    patterns = re.search(r"\\patterns\{(.*?)\n\}", text, re.S).group(1).split()
    exceptions = re.search(r"\\hyphenation\{(.*?)\n\}", text, re.S)
    exceptions = exceptions.group(1).split() if exceptions else []

    # The file is ASCII, and anything else in it would be a surprise worth stopping for.
    for word in patterns + exceptions:
        if not all(ord(c) < 128 for c in word):
            raise SystemExit(f"not ASCII: {word}")

    print(f"""// Generated by tools/make-hyphenation-tables.py from hyph-en-us.tex.
// Do not edit.
//
{NOTICE}

namespace n8PDF.Text;

/// <summary>
/// The patterns a word is broken by, and the words the patterns get wrong.
/// </summary>
/// <remarks>
/// Generated rather than written. Each pattern is a run of letters with numbers between them: the
/// numbers say how good a break is at that place, odd meaning allowed and even meaning not, and a
/// dot stands for the edge of a word. {len(patterns)} of them, and {len(exceptions)} words spelled
/// out in full because no pattern gets them right.
/// </remarks>
internal static class HyphenationTables
{{
    /// <summary>The patterns, separated by spaces.</summary>
    internal const string Patterns =
        \"\"\"
{wrap(patterns)}
        \"\"\";

    /// <summary>The words the patterns get wrong, hyphens marking where they may be broken.</summary>
    internal const string Exceptions =
        \"\"\"
{wrap(exceptions)}
        \"\"\";
}}""")


if __name__ == "__main__":
    main(sys.argv[1])
