#!/usr/bin/env python3
"""Writes the table of joining types the Arabic shaper reads.

An Arabic letter is drawn differently depending on what stands beside it, and which of the four
forms it takes is decided by whether its neighbours join at all. The Unicode character database
says which letters join on which side; this turns that into source, since the library carries no
dependencies and the answer must not depend on a file being present at run time.

    gh api repos/unicode-org/unicodetools/contents/unicodetools/data/ucd/15.0.0/ArabicShaping.txt \
        --jq '.content' | base64 -d > ArabicShaping.txt
    tools/make-arabic-tables.py ArabicShaping.txt > src/n8PDF/Text/JoiningTables.cs
"""

import sys
import unicodedata

KINDS = {"U": "None", "L": "Left", "R": "Right", "D": "Dual", "C": "Join", "T": "Transparent"}


def read(path):
    """The joining type of every character the database names."""
    types = {}

    for line in open(path, encoding="utf-8"):
        line = line.split("#")[0].strip()
        if not line:
            continue

        fields = [f.strip() for f in line.split(";")]
        if len(fields) < 3:
            continue

        types[int(fields[0], 16)] = fields[2]

    # Everything that is a mark and not named is transparent — it stands between two letters
    # without breaking the join between them, which is the whole of what transparent means.
    for code in range(0x0300, 0x110000):
        if code in types:
            continue
        if unicodedata.category(chr(code)) in ("Mn", "Me", "Cf"):
            types[code] = "T"

    return types


def ranges(types):
    out = []
    start = last = None
    kind = None

    for code in sorted(types):
        if kind == types[code] and code == last + 1:
            last = code
            continue

        if kind is not None:
            out.append((start, last, kind))

        start = last = code
        kind = types[code]

    out.append((start, last, kind))
    return out


rows = ranges(read(sys.argv[1]))

print(f"""// Generated by tools/make-arabic-tables.py from Unicode {unicodedata.unidata_version}. Do not edit.

namespace n8PDF.Text;

/// <summary>
/// Which side of itself each character joins on, from the Unicode character database.
/// </summary>
/// <remarks>
/// Generated rather than written, for the same reason the bidirectional tables are: the database
/// is the answer, and a table of several hundred entries typed by hand is several hundred chances
/// to be wrong about a letter nobody here can read.
/// </remarks>
internal static class JoiningTables
{{
    /// <summary>Where each run of characters of one joining type begins and ends.</summary>
    internal static readonly int[] Starts =
    [""")

def emit(values, per_line):
    for i in range(0, len(values), per_line):
        print("        " + " ".join(values[i:i + per_line]))

emit([f"0x{start:X}," for start, _, _ in rows], 12)
print("    ];\n")
print("    internal static readonly int[] Ends =\n    [")
emit([f"0x{end:X}," for _, end, _ in rows], 12)
print("    ];\n")
print("    internal static readonly Joining[] Kinds =\n    [")
emit([f"Joining.{KINDS[kind]}," for _, _, kind in rows], 8)
print("    ];")
print("}")
