#!/usr/bin/env python3
"""Generates the sRGB ICC profile the PDF/A output intent embeds (#68).

A minimal, valid ICC v2 display profile: sRGB primaries and white point, and the 2.2 gamma
curve that approximates sRGB's piecewise one. Written as a generated C# table so the library
ships bytes rather than takes a dependency; regenerate only if the profile needs to change.
"""
import struct, os

def s15(v): return struct.pack(">i", int(round(v * 65536)))

def tag_XYZ(x, y, z): return b"XYZ \0\0\0\0" + s15(x) + s15(y) + s15(z)

def tag_curv_gamma(g): return b"curv\0\0\0\0" + struct.pack(">I", 1) + struct.pack(">H", int(round(g * 256)))

def tag_desc(text):
    data = text.encode("ascii") + b"\0"
    return (b"desc\0\0\0\0" + struct.pack(">I", len(data)) + data + b"\0" * 12 + b"\0" * 67).ljust(90 + len(data) + 12, b"\0")

def tag_text(text): return b"text\0\0\0\0" + text.encode("ascii") + b"\0"

# sRGB primaries adapted to D50 (the values every sRGB profile carries).
tags = {
    b"desc": tag_desc("n8PDF sRGB"),
    b"cprt": tag_text("public domain"),
    b"wtpt": tag_XYZ(0.9642, 1.0, 0.8249),
    b"rXYZ": tag_XYZ(0.4360, 0.2225, 0.0139),
    b"gXYZ": tag_XYZ(0.3851, 0.7169, 0.0971),
    b"bXYZ": tag_XYZ(0.1431, 0.0606, 0.7139),
    b"rTRC": tag_curv_gamma(2.2),
    b"gTRC": tag_curv_gamma(2.2),
    b"bTRC": tag_curv_gamma(2.2),
}
tags[b"gTRC"] = tags[b"rTRC"]
tags[b"bTRC"] = tags[b"rTRC"]

order = [b"desc", b"cprt", b"wtpt", b"rXYZ", b"gXYZ", b"bXYZ", b"rTRC", b"gTRC", b"bTRC"]
unique = []
for name in order:
    if tags[name] not in [u[1] for u in unique]:
        unique.append((name, tags[name]))

table_count = len(order)
header_size = 128
table_size = 4 + table_count * 12
offset = header_size + table_size
offsets = {}
body = b""
for name, data in unique:
    padded = data + b"\0" * ((4 - len(data) % 4) % 4)
    offsets[bytes(data)] = (offset + len(body), len(data))
    body += padded

table = struct.pack(">I", table_count)
for name in order:
    at, size = offsets[bytes(tags[name])]
    table += name + struct.pack(">II", at, size)

size = header_size + len(table) + len(body)
header = struct.pack(">I", size)
header += b"n8pd"                       # preferred CMM
header += struct.pack(">I", 0x02400000)  # version 2.4
header += b"mntr"                        # display device
header += b"RGB "                        # data colour space
header += b"XYZ "                        # PCS
header += struct.pack(">HHHHHH", 2024, 1, 1, 0, 0, 0)
header += b"acsp"
header += b"\0" * 4                      # platform
header += struct.pack(">I", 0)           # flags
header += b"\0" * 8                      # manufacturer, model
header += struct.pack(">Q", 0)           # attributes
header += struct.pack(">I", 0)           # rendering intent: perceptual
header += s15(0.9642) + s15(1.0) + s15(0.8249)  # illuminant D50
header += b"\0" * 4                      # creator
header = header.ljust(128, b"\0")

profile = header + table + body
assert len(profile) == size, (len(profile), size)

out = os.path.join(os.path.dirname(__file__), "..", "src", "n8PDF", "Pdf", "SrgbIccProfile.cs")
lines = []
for i in range(0, len(profile), 16):
    lines.append("        " + ", ".join(f"0x{b:02X}" for b in profile[i:i+16]) + ",")
body_cs = "\n".join(lines).rstrip(",")
with open(os.path.normpath(out), "w") as f:
    f.write(f"""// <auto-generated>
// Generated by tools/make-icc-profile.py — do not edit by hand; fix the generator and re-run.
// </auto-generated>

namespace n8PDF.Pdf;

/// <summary>
/// The sRGB ICC profile the PDF/A output intent embeds (#68): a minimal, valid v2 display
/// profile — sRGB primaries and white point over a 2.2 gamma curve — generated rather than
/// shipped, so the library carries bytes and not a dependency.
/// </summary>
internal static class SrgbIccProfile
{{
    public static readonly byte[] Bytes =
    [
{body_cs}
    ];
}}
""")
print("wrote", os.path.normpath(out), size, "bytes")
