#!/usr/bin/env bash
#
# Produces the real-Word fixtures in tests/n8PDF.Tests/Fixtures/Real.
#
# Hand-authored fixtures contain only the markup we chose to write. Word documents contain far
# more: a styles.xml carrying every latent style, a settings.xml full of compatibility flags, a
# real theme, docProps, and whatever else Word decides belongs there. That is what these fixtures
# exist to test, and none of it can be produced by hand.
#
# So Word produces them. Each seed document is opened and saved straight back out as .docx, which
# rewrites the whole package in Word's own terms while leaving the content alone.
#
#   tools/make-real-fixtures.sh            regenerate the real fixtures
#   tools/make-real-fixtures.sh --list     show what would be generated and exit
#
# Requires macOS and Microsoft Word. Also generates a reference PDF for each, so the same fidelity
# comparison that covers the hand-authored fixtures covers these too.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SEEDS="$REPO_ROOT/artifacts/test-output/real-seeds"
REAL="$REPO_ROOT/tests/n8PDF.Tests/Fixtures/Real"
REFERENCES="$REPO_ROOT/tests/n8PDF.Tests/Fixtures/Reference"

LIST_ONLY=0
for arg in "$@"; do
    case "$arg" in
        --list) LIST_ONLY=1 ;;
        -h|--help) sed -n '2,20p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) echo "unknown option: $arg" >&2; exit 2 ;;
    esac
done

if [[ "$(uname)" != "Darwin" || ! -d "/Applications/Microsoft Word.app" ]]; then
    echo "This script needs macOS and Microsoft Word." >&2
    exit 1
fi

# The seeds are generated by the test suite, so make sure they are current before using them.
echo "Generating seed documents..."
dotnet test "$REPO_ROOT/n8PDF.sln" \
    --filter "FullyQualifiedName~Real_fixture_seeds_are_written" >/dev/null 2>&1 || true

shopt -s nullglob
seeds=("$SEEDS"/*.docx)
shopt -u nullglob

if [[ ${#seeds[@]} -eq 0 ]]; then
    echo "No seed documents in $SEEDS." >&2
    echo "Run 'dotnet test' once, then try again." >&2
    exit 1
fi

if [[ $LIST_ONLY -eq 1 ]]; then
    echo "Would round-trip ${#seeds[@]} document(s) through Word:"
    for seed in "${seeds[@]}"; do echo "  $(basename "$seed" .docx)"; done
    exit 0
fi

mkdir -p "$REAL" "$REFERENCES"

WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

echo "Round-tripping ${#seeds[@]} document(s) through Word..."
echo

failed=()
for seed in "${seeds[@]}"; do
    name="$(basename "$seed" .docx)"
    printf '  %-16s ' "$name"

    # Word is driven against a copy so that a failure cannot leave an owner-lock file in the
    # repository, and so the seed itself is never modified in place.
    cp "$seed" "$WORKDIR/$name.docx"

    out_docx="$WORKDIR/$name-word.docx"
    out_pdf="$WORKDIR/$name.pdf"
    rm -f "$out_docx" "$out_pdf"

    # The document is located by name rather than through "active document": if an earlier export
    # left something open, the active one is the wrong document and Word will happily save it
    # under this name, which is worse than failing because the result looks valid.
    error=$(osascript \
        -e 'on run argv' \
        -e '  set inFile to POSIX file (item 1 of argv)' \
        -e '  set docxPath to (item 2 of argv)' \
        -e '  set pdfPath to (item 3 of argv)' \
        -e '  set wanted to (item 4 of argv)' \
        -e '  with timeout of 300 seconds' \
        -e '    tell application "Microsoft Word"' \
        -e '      open inFile' \
        -e '      set theDoc to missing value' \
        -e '      repeat 60 times' \
        -e '        repeat with i from 1 to (count of documents)' \
        -e '          if name of document i is wanted then set theDoc to document i' \
        -e '        end repeat' \
        -e '        if theDoc is not missing value then exit repeat' \
        -e '        delay 0.5' \
        -e '      end repeat' \
        -e '      if theDoc is missing value then error "Word did not open a document named " & wanted' \
        -e '      save as theDoc file name pdfPath file format format PDF' \
        -e '      save as theDoc file name docxPath file format format document default' \
        -e '      repeat with i from (count of documents) to 1 by -1' \
        -e '        set n to name of document i' \
        -e '        if n is wanted or n ends with "-word.docx" then close document i saving no' \
        -e '      end repeat' \
        -e '    end tell' \
        -e '  end timeout' \
        -e 'end run' \
        "$WORKDIR/$name.docx" "$out_docx" "$out_pdf" "$name.docx" 2>&1) || true

    if [[ -s "$out_docx" && -s "$out_pdf" ]]; then
        mv "$out_docx" "$REAL/$name.docx"
        mv "$out_pdf" "$REFERENCES/real-$name.pdf"
        printf 'ok  (docx %s, pdf %s)\n' \
            "$(du -h "$REAL/$name.docx" | cut -f1 | tr -d ' ')" \
            "$(du -h "$REFERENCES/real-$name.pdf" | cut -f1 | tr -d ' ')"
    else
        printf 'FAILED\n'
        [[ -n "$error" ]] && printf '      %s\n' "$error"
        failed+=("$name")
    fi
done

echo
if [[ ${#failed[@]} -gt 0 ]]; then
    echo "Failed on ${#failed[@]} document(s):" >&2
    printf '  %s\n' "${failed[@]}" >&2
    echo >&2
    echo "If every one failed with 'Word did not open a document named ...', Word is wedged: it" >&2
    echo "accepts the open command and silently does nothing. Quit Word and re-run." >&2
    exit 1
fi

echo "Done. Word documents in:"
echo "  $REAL"
echo "and their reference PDFs alongside the others, prefixed 'real-'."
echo
echo "Now run: dotnet test"
